### ISSUE TITLE
CI test for asdf installation of jq already contains jq

### ISSUE THREAD

**Issue by AZMCode** [focused-labs/asdf-jq#3]
Related to #1
From the [latest ci before my pull request](https://github.com/focused-labs/asdf-jq/runs/691033401):  
```
jq  is already installed
jq-1.5-1-a5b5cbe
```
It seems the default asdf-plugin test cannot be used to test asdf-jq without modification, letting #1 slip through.

**Comment by AZMCode** [comment]
Same issue seems to be present in the macOS test

**Comment by smorimoto** [comment]
We just updated the README. https://github.com/asdf-vm/actions#trick-to-avoid-problems

**Comment by AZMCode** [comment]
Thanks
