### ISSUE TITLE
Installation on osx fails

### ISSUE THREAD

**Issue by mkv-ts** [focused-labs/asdf-jq#6]
Using the plugin on osx (zsh 5.7.1) fails with: .asdf/plugins/jq/bin/install: line 24: syntax error near unexpected token `;;'

To recreate:
```
asdf plugin add jq
echo 'jq jq-1.5' >> ~/.tool-versions
asdf install
```

Removing the whole definition of "local -r os..." and hardcoding "echo osx-amd64" fixes the issue.

**Comment by AZMCode** [comment]
Could you try with https://github.com/focused-labs/asdf-jq/pull/2? I believe it might fix your issue

**Comment by mkv-ts** [comment]
@AZMCode Not sure how to try that? Seems like the PR is closed and branch deleted?

**Comment by AZMCode** [comment]
Sorry for the inconvenience, the PR got out of hand. It seems this repo might change hands a bit, and no idea where. In the meantime, if you wish to, you can try my fork of it with the following command:
```
asdf plugin-add jq https://github.com/AZMCode/asdf-jq.git
```
It's pretty much an entire rewrite of the plugin, and I'll take in any issues you can find with it.

If you wish to try the old PR, it can be installed with the following commands:

```
asdf plugin-add jq https://github.com/AZMCode/asdf-jq
asdf plugin-update jq 504e3948670be9ead6fc9b55b0867aa51bde459b
```

**Comment by jritsema** [comment]
Thanks @AZMCode, this works for me.

**Comment by cehoffman** [comment]
Any update on repository changing hands and updating the default jq plugin for asdf?

**Comment by mkv-ts** [comment]
Closing this and moving on, as this repo seems dead anyway...
